### ISSUE TITLE
Refreshing the page logs out a user

### ISSUE THREAD

**Issue by Abdullah8006** [BrodyGaudel/bank#1]
After successfully login, a user is redirected to the operations page. When the operations page is refreshed, the users automatically logs out and the login page is again displayed.

**Comment by Abdullah8006** [comment]
According to my understanding the isLoggedIn is a normal variable and it
resets itself to false everytime the component loads. It's better to use
something like Subject or Behaviour Subject for this use case. I tried
implementing it but could because of my limited knowledge of Angular

**Comment by BrodyGaudel** [comment]
Good morning,
following the problem with authentication: I removed Spring Security and
JWT (while I found a solution).
You can now test the application.
User guide:
1- access the interface and click on “create a client”
2- after creating a client the system will ask you to choose the currency
of the client's bank account
3- once validated, you retrieve the bank account identifier which will be
useful in the operations management part.
4- you can also do a search by first or last name in the search space
located at the top right in the navbar.


NB: it is possible that some sentences are in French (I am French-speaking).

If you have comments, suggestions and opinions on the code: they are
welcome, it will help me a lot to improve.

Le mar. 3 oct. 2023 à 15:49, Abdullah Khan ***@***.***> a
écrit :

> According to my understanding the isLoggedIn is a normal variable and it
> resets itself to false everytime the component loads. It's better to use
> something like Subject or Behaviour Subject for this use case. I tried
> implementing it but could because of my limited knowledge of Angular
>

**Comment by BrodyGaudel** [comment]
solved
